import { describe, it, expect } from 'vitest';
import { CamService } from './CamService.js';
import { LaserTool, VectorOptions } from './Tools.js';

describe('CamService', () => {
    const service = new CamService();
    const laserTool: LaserTool = {
        id: 'test-laser',
        name: 'Test Laser',
        units: 'mm',
        type: 'laser',
        spotSize: 0.1,
        powerMax: 1000
    };

    it('generates G-code from SVG', async () => {
        // Use path d string (triangle)
        const svgContent = `<svg><path d="M 0 0 L 10 0 L 0 10 z" /></svg>`;
        const options: VectorOptions = {
            tool: laserTool,
            format: 'svg',
            feedrate: 1500
        };

        const gcode = await service.generateVector(svgContent, options);
        expect(gcode).toContain('; Generated by RevivedLaserweb4 (Vector)');
        expect(gcode).toContain('G21');
        expect(gcode).toContain('F1500');
        expect(gcode).toContain('M3 S0');
        // Check for coordinates (rough check)
        expect(gcode).toContain('X10');
    });

    it('throws error for invalid vector', async () => {
        const options: VectorOptions = {
            tool: laserTool,
            format: 'svg',
            feedrate: 1000
        };
        await expect(service.generateVector('invalid-xml', options)).rejects.toThrow();
    });
});
